version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixelwar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pixel_service:
    build: ./backend/pixel_service
    container_name: pixel_service
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres/pixelwar
    env_file:
      - ./backend/pixel_service/.env
    ports:
      - "8000:8000"

  event_service:
    build: ./backend/event_service
    container_name: event_service
    depends_on:
      - redis
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - pixel_service
      - event_service
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
