version: "3.8"

services:
  haproxy:
    image: haproxy:latest
    build: 
      context: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg 
    deploy:
      replicas: 1
    networks:
      - ws-network
    depends_on:
      - event_service
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixelwar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  pixel_service:
    build:
      context: ./backend/pixel_service
      dockerfile: Dockerfile
    image: pixel_service_image:latest
    depends_on:
      - redis
      - postgres
      - event_service
    env_file:
      - ./backend/pixel_service/.env
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - backend
      - frontend

  event_service:
    build:
      context: ./backend/event_service
      dockerfile: Dockerfile
    image: event_service_image:latest
    depends_on:
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8001" # Direktzugriff auf den Event-Service
    networks:
      - backend
      - frontend
      - ws-network

  frontend:
    build:
      context: ./frontend
    image: frontend_image:latest
    ports:
      - "3000:3000"
    depends_on:
      - pixel_service
      - event_service
    environment:
      - NODE_ENV=production
    networks:
      - frontend

volumes:
  postgres_data:

networks:
  backend:
  frontend:
  ws-network:
    driver: overlay